### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by satouriko** [RBQUniversity/About#14]
Truly, I am committed to this intellectual journey, and to the University of RBQ 
itself. Attending the 
University of RBQ for Japanese studies is a natural step for me, one I’m prepared 
to take and work tirelessly for, with both diligence and alacrity. I’ve made my decision. 
Now, I look forward to yours

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
