### ISSUE TITLE
申请加入 RBQ 大学

### ISSUE THREAD

**Issue by bobby285271** [RBQUniversity/About#19]
亲爱的 RBQ 大学：
您好！我志愿加入 RBQ 大学，体验全球一流 RBQ 教育！为 RBQ 奋斗终身！
　　
此致
敬礼
bobby285271

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
