### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by Xeonacid** [RBQUniversity/About#24]
亲爱的 RBQ 大学：  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您好！我志愿加入 RBQ 大学，体验全球一流 RBQ 教育！为 RBQ 奋斗终身！  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此致  
敬礼  
Xeonacid

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
