### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by cutedogetech** [RBQUniversity/About#41]
亲爱的 RBQ 大学：  

您好！我志愿加入 RBQ 大学，体验全球一流 RBQ 教育，并且想稍微了解是否需要干什么。为 RBQ 奋斗终身！  

此致  
敬礼  
临睦

**Comment by KevinZonda** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
