### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by alphagocc** [RBQUniversity/About#6]
Dear RBQ University Headmaster:

As we all know, becoming a student of RBQ University has many adavantages, espcially in how to be a better RBQ. RBQ University provides us with the fabulous RBQ Training Centre in the world and you can learn any knowledge about RBQ, without any limitation. The rapid increase in students has also proved your high education quality. Though I am only a normal hentai which has no talents for being an RBQ, I also want to enter the school.

PS: Have you ever considered cooperating with Shimokitazawa University , a university famous for making black tea

Yours sincerely

Li Hua

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University

**Comment by KevinZonda** [comment]
So what's Shimokitazawa University?

**Comment by alphagocc** [comment]
It's a university of homo :P
