### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by EnabledFish** [RBQUniversity/About#93]
Dear whom may concern,

Hello. I want to join RBQ University to study how to become an RBQ!

Regards,  
EnabledFish

**Comment by EnabledFish** [comment]
@KevinZonda

![1FD~K6X049 R@IM$3S@1~~4](https://user-images.githubusercontent.com/70457081/173178230-7766e6d8-eee3-44e9-bcf6-9cab017ac0e9.gif)

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
