### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by thuongtruong1009** [RBQUniversity/About#98]
Dear whom may concern,
My name is Tran Nguyen Thuong Truong

Hello. I want to join RBQ University to study how to become an RBQ!

Regards,  
Your Name

**Comment by AkinoKaede** [comment]
Hi,
Congratulations! Your application has been accepted and the offer has been sent to your mail. Please confirm the offer or the invitation within 7 days.

Regards,
RBQ University
